#!/usr/bin/env bash
# Fetches X11 rgb.txt and generates hued-names.sh.
# Run this to regenerate after updating the source list.
set -euo pipefail

URL="https://gitlab.freedesktop.org/xorg/app/rgb/-/raw/master/rgb.txt"
OUT="$(dirname "$0")/../hued-names.sh"

{
  echo "# Generated by scripts/generate-names.sh — do not edit by hand"
  echo "# Source: $URL"
  echo "declare -A _HUED_NAMES=("
  curl -sf "$URL" | while read -r r g b name; do
    [[ "$r" =~ ^[0-9]+$ ]] || continue
    name_lower="${name,,}"          # lowercase
    name_key="${name_lower// /}"    # strip spaces
    printf "  [%s]=#%02x%02x%02x\n" "$name_key" "$r" "$g" "$b"
  done | sort -u
  echo ")"
} > "$OUT"

echo "Generated $OUT"
