"""One-shot: parse src/picker/lib/names.ts (TS) into src/picker/names.py.

Run manually once: python3 scripts/names_to_py.py
The output file is committed; this script is not part of the build.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "picker" / "lib" / "names.ts"
DST = ROOT / "src" / "picker" / "names.py"

if not SRC.exists():
    sys.exit(f"missing {SRC} — checkout feature/interactive-mode to get it")

pattern = re.compile(r'"([a-z0-9]+)":\s*"(#[0-9a-fA-F]{6})"')
pairs = pattern.findall(SRC.read_text())
if not pairs:
    sys.exit("no entries parsed; check the TS file format")

lines = ["# Generated by scripts/names_to_py.py from src/picker/lib/names.ts",
         "# Do not edit directly.",
         "",
         "NAMED_COLORS: dict[str, str] = {"]
for name, hex_val in pairs:
    lines.append(f'    "{name}": "{hex_val.lower()}",')
lines.append("}")
lines.append("")
DST.write_text("\n".join(lines))
print(f"wrote {len(pairs)} entries to {DST}")
